#!/bin/bash

# No cleanups on package upgrades
if [[ $1 == upgrade ]] || [[ $1 == failed-upgrade ]] || [[ $1 == abort-upgrade ]]
then
	exit 0
fi

# Cleanup state-keeping directory
stateDirectory="/var/lib/APTHistoryLogger"
if [[ -d $stateDirectory ]]
then
	rm -r ${stateDirectory}
	if [[ $? != 0 ]]
	then
		echo "Warning: failed to remove state directory $stateDirectory"
	fi
fi

# Cleanup systemd /lib
serviceUnitFile="/lib/systemd/system/apthl.service"
if [[ -f $serviceUnitFile ]]
then
	rm ${serviceUnitFile}
	if [[ $? != 0 ]]
	then
		echo "Warning: failed to remove systemd unit file $serviceUnitFile"
	fi
fi

# Reload systemd
systemctl daemon-reload
if [[ $? != 0 ]]
then
	echo "Warning: failed to reload systemd daemons"
fi

exit 0
